# Puerto único para el microservicio de Reseñas
server.port=8089

# Conexión a Laragon MySQL (Puerto 3306) creando la BD de reseñas
spring.datasource.url=jdbc:mysql://localhost:3306/petbox_resenas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true